byway/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls',namespace='web')),
    path('users/', include('users.urls',namespace='users')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import login, logout, signup


app_name = 'users' 

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup')
]

web/urls.py
from django.urls import path
from .views import home, course_details, top_courses, category_details, instructor_courses


app_name = 'web' 

urlpatterns = [
    path('', home, name='home'), 
    path('course/<int:id>/', course_details, name='course_details'),
    path('topcourse/', top_courses, name='top_courses'),
    path('category/<int:category_id>/', category_details, name='category_details'),
    path('instructor/<int:instructor_id>/', instructor_courses, name='instructor_courses'),
]

users/models.py
from django.db import models

# Create your models here.

web/models.py
from django.db import models

class Testimonial(models.Model):
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=100)
    image = models.ImageField(upload_to='testimonials/')
    description = models.TextField()

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.name


class Categories(models.Model):
    name = models.CharField(max_length=100)
    icon = models.FileField(upload_to='categories/')

    def __str__(self):
        return self.name


class Instructors(models.Model):
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=100)
    image = models.ImageField(upload_to='instructors/', blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    rating = models.FloatField(default=0.0)  
    students = models.IntegerField(default=0)
    courses_count = models.IntegerField(default=0)
    reviews = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Languages(models.Model):
    languages = models.CharField(max_length=50)

    def __str__(self):
        return self.languages


class Courses(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='courses/')  
    description = models.TextField()
    certification = models.TextField()
    rating = models.FloatField(default=0.0)
    rating_count = models.IntegerField()
    duration = models.TextField()  
    instructor = models.ForeignKey('Instructors', on_delete=models.CASCADE)
    languages = models.ManyToManyField('Languages', related_name='courses')
    price = models.DecimalField(max_digits=10, decimal_places=1) 
    discount_percent = models.DecimalField(max_digits=2, decimal_places=0, default=0.0) 
    categories = models.ManyToManyField(Categories, related_name='courses', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def discounted_price(self):
        discount = (self.discount_percent / 100) * self.price
        return round(self.price - discount, 2)

    class Meta:
            ordering = ["id"]


class Syllabus(models.Model):
    course = models.ForeignKey('Courses', related_name='syllabi', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    lessons = models.IntegerField(null=True)  
    duration = models.CharField(max_length=50, null=True)


    def __str__(self):
        return self.title

users/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Password',
        })
    )
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({
            'placeholder': 'First Name'
        })
        self.fields['last_name'].widget.attrs.update({
            'placeholder': 'Last Name'
        })
        self.fields['username'].widget.attrs.update({
            'placeholder': 'Username'
        })
        self.fields['email'].widget.attrs.update({
            'placeholder': 'Email Address'
        })

users/views.py
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User

from users.forms import UserForm

def login(request):
    context = {'title': 'Login'}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(reverse('web:home'))

        context.update({
            'error': True,
            'message': 'Invalid username or password',
        })

    return render(request, 'users/login.html', context)

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('web:home'))

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            User.objects.create_user(
                username=instance.username,
                email=instance.email,
                first_name=instance.first_name,
                last_name=instance.last_name,
                password=instance.password
            )
             
            user = authenticate(request, username=instance.username, password=instance.password)
            auth_login(request, user)

            return HttpResponseRedirect(reverse('web:home'))
    else:
        form = UserForm()
        context = {
            'title': 'Signup',
            'form': form
        }
    return render(request, 'users/signup.html', context=context)

web/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from web.models import Testimonial, Categories, Instructors, Courses, Syllabus


def home(request):
    testimonials = Testimonial.objects.all()
    categories = Categories.objects.annotate(courses_count=Count('courses'))
    instructors = Instructors.objects.all()
    top_instructors = instructors[:5] 
    remaining_instructors = instructors[5:]
    courses = Courses.objects.all()

    context = {
        'testimonials': testimonials,
        'categories': categories,
        'top_instructors': top_instructors,
        'remaining_instructors': remaining_instructors,
        'courses': courses
    }
    
    return render(request, 'web/index.html', context=context)


def course_details(request, id):
    testimonials = Testimonial.objects.all()
    course = get_object_or_404(Courses, id=id)
    syllabi = course.syllabi.all()
    courses = Courses.objects.all()



    context = {
        'course': course,
        'testimonials': testimonials,
        'syllabi': syllabi,
        'courses': courses
    }

    return render(request, 'web/details.html', context=context)


def top_courses(request):
    courses = Courses.objects.all()

    context = {
        'courses': courses
    }
    
    return render(request, 'web/topCourses.html', context=context)


def category_details(request, category_id):
    category = get_object_or_404(Categories, id=category_id)
    courses = category.courses.all()

    return render(request, 'web/category_details.html', {'category': category, 'courses': courses})


def instructor_courses(request, instructor_id):
    instructor = get_object_or_404(Instructors, id=instructor_id)
    courses = Courses.objects.filter(instructor=instructor)
    
    context = {
        'instructor': instructor,
        'courses': courses,
    }
    return render(request, 'web/instructor_courses.html', context)

templates/users/login.html
{% extends 'users/auth_base.html' %} {% load static %} {% block title %}ByWay |
Login{% endblock %} {% block content %}
<div class="main_container">
  <div class="logo_container">
    <a href="{% url 'web:home' %}">
      <span>
        <img
          src="{% static 'assets/icons/logo.svg' %}"
          alt=" Logo"
          class="logo"
        />
      </span>
      <span>Byway</span>
    </a>
  </div>
  <div class="text_container">
    <h1>Welcome to Byway</h1>
    <h6>Your gateway to limitless learning</h6>
  </div>
  <div class="bottom">
    <form action="" method="post">
      {% csrf_token %}
      <div class="input_container">
        <label for="id_username">Username or Email</label>
        <input
          id="id_username"
          name="username"
          type="text"
          placeholder="Enter your username or email"
        />
      </div>
      <div class="input_container">
        <label for="id_password">Password</label>
        <input
          id="id_password"
          name="password"
          type="password"
          placeholder="Enter your password"
        />
      </div>
      <div class="forgot-password_container">
        <a href="">Forgot Password?</a>
      </div>
      <div class="submit_container">
        {% if error %}
        <p class="error-message">{{message}}</p>
        {% endif %}
        <button type="submit">Login</button>
      </div>
    </form>
    <div class="sign-up_container">
      <a href="{% url 'users:signup' %}">Don't have an account? Sign Up</a>
    </div>
  </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends 'users/auth_base.html' %} {% load static %} {% block title %}ByWay |
Signup{% endblock %}{% block content %}
<div class="main_container">
  <div class="logo_container">
    <a href="./details.html">
      <span>
        <img
          src="{% static 'assets/icons/logo.svg' %}"
          alt=" Logo"
          class="logo"
        />
      </span>
      <span>Byway</span>
    </a>
  </div>
  <div class="text_container">
    <h1>Create an account</h1>
    <h6>Join Byway today and unlock limitless learning</h6>
  </div>
  <div class="bottom">
    <form action="" method="post">
      {% csrf_token %} {% for field in form %}
      <div class="input_container_signup">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>

        {{ field }} {% if field.errors %}
        <div class="error">{{ field.errors }}</div>
        {% endif %}
      </div>
      {% endfor %}
      <div class="submit_container">
        <button type="submit">Signup</button>
      </div>
    </form>
    <div class="sign-up_container">
      <a href="{% url 'users:login' %}">Do you have an account? Login</a>
    </div>
  </div>
</div>
{% endblock %}

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% block extra_css %}{% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
    />
    <link
      rel="icon"
      href="{% static 'assets/icons/logo.svg' %}"
      type="image/png"
    />
    <title>{% block title %}Byway{% endblock %}</title>
  </head>
  <body>
    <header>
      <div class="wrapper">
        <div class="logo-container">
          <a href="{% url 'web:home' %}">
            <span>
              <img
                src="{% static 'assets/icons/logo.svg' %}"
                alt=" Logo"
                class="logo"
              />
            </span>
            <span>Byway</span>
          </a>
        </div>
        <div class="account-container">
          {% if request.user.is_authenticated %}
          <a href="#" class="cart-icon">
            <img
              src="{% static 'assets/icons/wishlist.svg' %}"
              alt="wishlist icon"
            />
          </a>
          <a href="#" class="cart-icon">
            <img
              src="{% static 'assets/icons/cart.svg' %}"
              alt="cart icon"
            /> </a
          ><a href="#" class="cart-icon">
            <img src="{% static 'assets/icons/bell.svg' %}" alt="cart icon" />
          </a>
          <a href="#" class="account">{{ request.user.first_name|default:request.user.username|slice:":1" }}</a>
          <a href="{% url 'users:logout' %}" class="log-in">log out</a>
          {% else %}
          <span class="cart-icon">
            <img src="{% static 'assets/icons/cart.svg' %}" alt="cart icon" />
          </span>
          <a href="{% url 'users:login' %}" class="log-in">log in</a>
          <a href="#" class="sign-up">sign up</a>
          {% endif %}
        </div>
      </div>
    </header>
    <!-- add block -->

    {% block content %}
    <!-- Default content -->
    {% endblock %}

    <!-- endblock -->

    <footer>
      <div class="wrapper">
        <div class="items">
          <div class="item item1">
            <a href="{% url 'web:home' %}" class="logo">
              <img src="{% static 'assets/icons/logo-big.svg' %}" alt="icon" />
            </a>
            <p>
              Empowering learners through accessible and engaging online
              education. <br />
              Byway is a leading online learning platform dedicated to providing
              high-quality, flexible, and affordable educational experiences.
            </p>
          </div>
          <div class="item item2">
            <h5>Get Help</h5>
            <ul>
              <li>
                <a href="">Contact Us</a>
              </li>
              <li>
                <a href="">Latest Articles</a>
              </li>
              <li>
                <a href="">FAQ</a>
              </li>
            </ul>
          </div>
          <div class="item item3">
            <h5>Programs</h5>
            <ul>
              <li>
                <a href="">Art & Design</a>
              </li>
              <li>
                <a href="">Business</a>
              </li>
              <li>
                <a href="">IT & Software</a>
              </li>
              <li>
                <a href="">Languages</a>
              </li>
              <li>
                <a href="">Programming</a>
              </li>
            </ul>
          </div>
          <div class="item item4">
            <h5>Contact Us</h5>
            <ul>
              <li>
                <a href="">Address: 123 Main Street, Anytown, CA 12345</a>
              </li>
              <li><a href="">Tel: +(123) 456-7890</a></li>
              <li>
                <a href="mailto:bywayedu@webkul.in">Mail: bywayedu@webkul.in</a>
              </li>
            </ul>
            <div class="social-media">
              <ul>
                <li>
                  <a href="https://www.facebook.com/" target="_blank"
                    ><img
                      src="{% static 'assets/icons/facebook.png' %}"
                      alt="facebook"
                  /></a>
                </li>
                <li>
                  <a href="https://github.com/" target="_blank"
                    ><img
                      src="{% static 'assets/icons/github.png' %}"
                      alt="github"
                  /></a>
                </li>
                <li>
                  <a href="https://www.google.co.in/" target="_blank"
                    ><img
                      src="{% static 'assets/icons/google.png' %}"
                      alt="google"
                  /></a>
                </li>
                <li>
                  <a href="https://x.com" target="blank"
                    ><img
                      src="{% static 'assets/icons/twitter.png' %}"
                      alt="twitter"
                  /></a>
                </li>
                <li>
                  <a href="https://www.microsoft.com" target="blank"
                    ><img
                      src="{% static 'assets/icons/microsoft.png' %}"
                      alt="microsoft"
                  /></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <!-- JavaScript files -->
    {% block extra_js %} {% endblock %}
  </body>
</html>

templates/web/category_details.html
{% extends 'web/base.html' %} {% load static %} {% block title %}ByWay |
Top-Courses{% endblock %} {% block content %}

<section class="top-courses">
  <div class="wrapper">
    <div class="top">
      <h3>Courses in {{ category.name }}</h3>
    </div>
    <div class="widgets">
      {% for course in courses %}
      <a href="{% url 'web:course_details' course.id %}" class="card">
        <div class="content-wrapper">
          <div class="image-wrapper">
            <img src="{{course.image.url}}" alt="image" />
          </div>
          <h5 class="course-title" data-full-title="{{ course.title }}">{{ course.title }}</h5>
          <p>{{course.instructor}}</p>
          <div class="rating-container">
            <span class="rating">{{ course.rating }}</span>
            <span class="star star-rating-container"></span>
            <small>({{course.rating_count}} Ratings)</small>
          </div>
          <p class="duration" data-full-duration="{{ course.duration }}">{{course.duration}}</p>
          <h4>${{course.discounted_price}}</h4>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'css/topCourses.css' %}" />
{% endblock %} {% block extra_js %}
<script type="module" src="{% static 'javascript/starRating.js' %}"></script>
<script src="{% static 'javascript/truncateTitle.js' %}"></script>
{% endblock %}

templates/web/index.html
{% extends 'web/base.html' %} {% load static %} {% block title %}ByWay{% endblock %}
{% block content %}
<!-- sportlight -->
<section class="sportlight">
  <div class="wrapper">
    <div class="left">
      <h1>Unlock Your Potential with Byway</h1>
      <p>
        Welcome to Byway, where learning knows no bounds. We believe that
        education is the key to personal and professional growth, and we're here
        to guide you on your journey to success.
      </p>
      <a href="" class="button"> Start your instructor journey </a>
    </div>
    <div class="right">
      <div class="image-wrapper">
        <img
          src="{% static 'assets/images/sportlight.png' %}"
          alt="Sportlight image"
        />
      </div>
    </div>
  </div>
</section>

<!-- couse-details -->

<section class="course-counts">
  <div class="wrapper">
    <div class="items">
      <div class="item">
        <h2>250+</h2>
        <p>Courses by our best mentors</p>
      </div>
      <div class="item">
        <h2>1000+</h2>
        <p>Courses by our best mentors</p>
      </div>
      <div class="item">
        <h2>15+</h2>
        <p>Courses by our best mentors</p>
      </div>
      <div class="item">
        <h2>2400+</h2>
        <p>Courses by our best mentors</p>
      </div>
    </div>
  </div>
</section>

<!-- categories-section -->

<section class="main">
  <div class="wrapper">
    <!-- top categories -->
    <div class="top-categories">
      <div class="top">
        <h3>Top Categories</h3>
        <a href="#" class="see-all">See All</a>
      </div>
      <div class="widgets">
        {% for category in categories %}
        <a href="{% url 'web:category_details' category.id %}" class="card">
          <div class="content-wrapper">
            <span class="round-bg">
              <img src="{{category.icon.url}}" alt="astrology-icon" />
            </span>
            <h4>{{category.name}}</h4>
            <p>{{category.courses.count}}</p>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>

    <!-- top courses -->
    <div class="top-courses">
      <div class="top">
        <h3>Top Courses</h3>
        <a href="{% url 'web:top_courses' %}" class="see-all">See All</a>
      </div>
      <div class="widgets">
        {% for course in courses|slice:"4" %}
        <a href="{% url 'web:course_details' course.id %}" class="card">
          <div class="content-wrapper">
            <div class="image-wrapper">
              <img src="{{course.image.url}}" alt="Course image" />
            </div>
            <h5>{{ course.title|truncatewords:10 }}</h5>
            <p>{{ course.instructor }}</p>
            <div class="rating-container">
              <span class="rating">{{ course.rating }}</span>
              <span class="star star-rating-container"></span>
              <small>({{ course.rating_count }} Ratings)</small>
            </div>
            <p class="duration">{{ course.duration }}</p>
            <h4>${{ course.discounted_price }}</h4>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>

    <!-- top instructors -->
    <div class="top-instructors">
      <div class="top">
        <h3>Top Instructors</h3>
        <a href="#" class="see-all" id="see-all-button">See All</a>
      </div>
      <div class="widgets">
        {% for instructor in top_instructors %}
        <a href="{% url 'web:instructor_courses' instructor.id %}" class="card">
          <div class="content-wrapper">
            <div class="image-wrapper">
              <img src="{{ instructor.image.url }}" alt="Instructor image" />
            </div>
            <h5>{{ instructor.name }}</h5>
            <small>{{ instructor.designation }}</small>
            <span class="line"></span>
            <div class="rating-box">
              <span class="star-box">
                <img
                  src="{% static 'assets/icons/star.svg' %}"
                  alt="Star icon"
                />
                <label for="">{{ instructor.rating }}</label>
              </span>
              <span class="students-count">
                <small>{{ instructor.students }} Students</small>
              </span>
            </div>
          </div>
        </a>
        {% endfor %}

        <!-- Hidden instructors -->
        <div
          class="top-instructors"
          id="remaining-instructors"
          style="display: none"
        >
          <div class="widgets">
            {% for instructor in remaining_instructors %}
            <a
              href="{% url 'web:instructor_courses' instructor.id %}"
              class="card"
            >
              <div class="content-wrapper">
                <div class="image-wrapper">
                  <img src="{{ instructor.image.url }}" alt="image" />
                </div>
                <h5>{{ instructor.name }}</h5>
                <small>{{ instructor.designation }}</small>
                <span class="line"></span>
                <div class="rating-box">
                  <span class="star-box">
                    <img
                      src="{% static 'assets/icons/star.svg' %}"
                      alt="star"
                    />
                    <label for="">{{ instructor.rating }}</label>
                  </span>
                  <span class="students-count">
                    <small>{{ instructor.students }}</small>
                  </span>
                </div>
              </div>
            </a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- testimonials -->
<section class="testimonials">
  <div class="wrapper">
    <div class="top">
      <div class="heading-container">
        <h3>What Our Customer Say About Us</h3>
      </div>
      <div class="navigation">
        <span
          class="custom-swiper-button-prev"
          role="button"
          aria-label="Previous slide"
          tabindex="0"
        >
          <img
            src="{% static 'assets/icons/short-arrow-left.svg' %}"
            alt="left-arrow"
          />
        </span>
        <span
          class="custom-swiper-button-next"
          role="button"
          aria-label="Next slide"
          tabindex="0"
        >
          <img
            src="{% static 'assets/icons/short-arrow-right.svg' %}"
            alt="right-arrow"
          />
        </span>
      </div>
    </div>
    <div class="contents">
      <div class="swiper">
        <div class="items swiper-wrapper">
          {% for testimonial in testimonials %}
          <a href="#" class="item swiper-slide">
            <span class="quote">
              <img
                src="{% static 'assets/icons/quotes.svg' %}"
                alt="quote-icon"
              />
            </span>
            <p>"{{testimonial.description}}"</p>
            <div class="author-info">
              <span class="author-profile">
                <img src="{{ testimonial.image.url}}" alt="image" />
              </span>
              <div class="text">
                <h5>{{testimonial.name}}</h5>
                <small>{{testimonial.designation}}</small>
              </div>
            </div>
          </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>

<!-- more -->

<section class="more-about">
  <div class="wrapper">
    <div class="top-section">
      <div class="left-img">
        <img src="{% static 'assets/images/model-4.jpg' %}" alt="image" />
      </div>
      <div class="right-content">
        <h4>Become an Instructor</h4>
        <p>
          Instructors from around the world teach millions of students on Byway.
          We provide the tools and skills to teach what you love.
        </p>
        <a href="" class="button">
          <small>Start Your Instructor Journey</small>
          <span
            ><img src="{% static 'assets/icons/arrow-right.svg' %}" alt="icon"
          /></span>
        </a>
      </div>
    </div>

    <div class="bottom-section">
      <div class="left-content">
        <h4>Transform your life through education</h4>
        <p>
          Learners around the world are launching new careers, advancing in
          their fields, and enriching their lives.
        </p>
        <a href="" class="button">
          <small>Checkout Courses</small>
          <span
            ><img src="{% static 'assets/icons/arrow-right.svg' %}" alt="icon"
          /></span>
        </a>
      </div>
      <div class="right-img">
        <img src="{% static 'assets/images/model-6.jpg' %}" alt="image" />
      </div>
    </div>
  </div>
</section>

{% endblock %} {% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<script type="module" src="{% static 'javascript/starRating.js' %}"></script>
<script src="{% static 'javascript/swiper.js' %}"></script>
<script src="{% static 'javascript/home.js' %}"></script>
{% endblock %}

templates/web/instructor_courses.html
{% extends 'web/base.html' %} {% load static %} {% block title %}ByWay | Instructors{% endblock %} {% block content %}

<section class="top-courses">
  <div class="wrapper">
    <div class="top">
      <h3>Courses by {{ instructor.name }}</h3>
    </div>
    <div class="widgets">
      {% for course in courses %}
      <a href="{% url 'web:course_details' course.id %}" class="card">
        <div class="content-wrapper">
          <div class="image-wrapper">
            <img src="{{course.image.url}}" alt="image" />
          </div>
          <h5 class="course-title" data-full-title="{{ course.title }}">{{ course.title }}</h5>
          <p>{{course.instructor}}</p>
          <div class="rating-container">
            <span class="rating">{{ course.rating }}</span>
            <span class="star star-rating-container"></span>
            <small>({{course.rating_count}} Ratings)</small>
          </div>
          <p class="duration" data-full-duration="{{ course.duration }}">{{course.duration}}</p>
          <h4>${{course.discounted_price}}</h4>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'css/topCourses.css' %}" />
{% endblock %} {% block extra_js %}
<script type="module" src="{% static 'javascript/starRating.js' %}"></script>
<script src="{% static 'javascript/truncateTitle.js' %}"></script>
{% endblock %}

templates/web/topCourses.html
{% extends 'web/base.html' %} {% load static %} {% block title %}ByWay | Top-Courses{% endblock %} {% block content %}

<section class="top-courses">
  <div class="wrapper">
    <div class="top">
      <h3>Top Courses</h3>
    </div>
    <div class="widgets">
      {% for course in courses %}
      <a href="{% url 'web:course_details' course.id %}" class="card">
        <div class="content-wrapper">
          <div class="image-wrapper">
            <img src="{{course.image.url}}" alt="image" />
          </div>
          <h5 class="course-title" data-full-title="{{ course.title }}">{{ course.title }}</h5>
          <p>{{course.instructor}}</p>
          <div class="rating-container">
            <span class="rating">{{ course.rating }}</span>
            <span class="star star-rating-container"></span>
            <small>({{course.rating_count}} Ratings)</small>
          </div>
          <p class="duration" data-full-duration="{{ course.duration }}">{{course.duration}}</p>
          <h4>${{course.discounted_price}}</h4>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'css/topCourses.css' %}" />
{% endblock %} {% block extra_js %}
<script type="module" src="{% static 'javascript/starRating.js' %}"></script>
<script src="{% static 'javascript/truncateTitle.js' %}"></script>
{% endblock %}